name: Build DeathChest Plugin  # Friendly name shown in GitHub UI

on: 
  push:  # Triggers when you push code
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4  # Checks out your code
    
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Build with Maven
      run: mvn clean package  # Compiles the plugin
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: DeathChest.jar
        path: target/*.jar  # Path where Maven saves the JAR
